const mongoose = require('mongoose')
mongoose.Promise = require('bluebird')
const Happening = require('../models/Happening')
const User = require('../models/User')
const happeningData = require('./data/happeningData')
const usersData = require('./data/usersData')
const { dbURI } = require('../config/environment')

mongoose.connect(dbURI, { useNewUrlParser: true })
  .then(() => mongoose.connection.db.dropDatabase())
  .then(() => Happening.create(happeningData))
  .then(() => User.create(usersData))
  .then(() => console.log('Successfully seeded!'))
  .catch((err) => console.log(err))
  .finally(() => mongoose.connection.close())
